name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
      - run: actions/checkout@v4
      - name: Set up Node.js
      - run: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
      - run: yarn install
      - name: Build the app
      - run: yarn build
      - name: Deploy to server
      - run: scp -r build/* root@212.192.9.251:/var/www/react-app